# Generated by Django 2.2.7 on 2019-12-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='designation',
            field=models.CharField(choices=[('grand_orgue', 'Grand orgue'), ('orgue_choeur', 'Orgue de chœur'), ('orgue', 'Orgue')], default='Orgue', max_length=300, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='elevation',
            field=models.CharField(blank=True, choices=[('sol', 'Au sol'), ('tribune', 'En tribune')], max_length=20, null=True, verbose_name='Elévation'),
        ),
    ]
