# Generated by Django 2.2.13 on 2020-07-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='designation',
            field=models.CharField(default='orgue', max_length=300, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='resume',
            field=models.TextField(blank=True, help_text="Présentation en quelques lignes de l'instrument                               et son originalité (max 500 caractères)", max_length=500, null=True, verbose_name='Resumé'),
        ),
    ]
