# Generated by Django 2.2.13 on 2020-07-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0002_auto_20200730_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='proprietaire',
            field=models.CharField(choices=[('commune', 'Commune'), ('etat', 'Etat'), ('association_culturelle', 'Association culturelle'), ('diocese', 'Diocèse'), ('paroisse', 'Paroisse')], default='commune', max_length=20, null=True),
        ),
    ]
