# Generated by Django 2.2.13 on 2020-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0003_auto_20200730_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='commentaire_tuyauterie',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la tuyauterie'),
        ),
    ]
