# Generated by Django 2.2.13 on 2020-07-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0004_auto_20200730_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='lien',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lien'),
        ),
    ]
