# Generated by Django 2.2.7 on 2020-02-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0005_auto_20200210_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgue',
            name='boite_expressive',
        ),
    ]
