# Generated by Django 2.2.7 on 2020-02-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0006_remove_orgue_boite_expressive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgue',
            options={'ordering': ['-created_date'], 'permissions': [('change_localisation', "Peut modifier les informations de localisation d'un orgue")]},
        ),
    ]
