# Generated by Django 2.2.13 on 2020-08-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0007_auto_20200730_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='buffet',
            field=models.TextField(blank=True, help_text='Description du buffet et de son état.', null=True, verbose_name='Description du buffet'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='codification',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='console',
            field=models.TextField(blank=True, help_text="Description de la console (ex: en fenêtre,                                séparée organiste tourné vers l'orgue ...).", null=True, verbose_name='Description de la console'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='diapason',
            field=models.CharField(blank=True, help_text='Hauteur en Hertz du A2 joué par le prestant 4, à une température donnée', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='proprietaire',
            field=models.CharField(choices=[('commune', 'Commune'), ('etat', 'Etat'), ('association_culturelle', 'Association culturelle'), ('diocese', 'Diocèse'), ('paroisse', 'Paroisse')], default='commune', max_length=20, null=True, verbose_name='Propriétaire'),
        ),
    ]
