# Generated by Django 2.2.13 on 2020-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0007_auto_20200730_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='codification',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
