# Generated by Django 2.2.13 on 2020-08-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0008_auto_20200812_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='lien',
            field=models.URLField(blank=True, verbose_name='Lien'),
        ),
    ]
