# Generated by Django 2.2.7 on 2020-02-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0009_orgue_accessoires'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='configuration',
            field=models.CharField(blank=True, choices=[('basse', 'Basse'), ('dessus', 'Dessus')], max_length=20, null=True),
        ),
    ]
