# Generated by Django 2.2.7 on 2020-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0009_auto_20200812_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgue',
            old_name='resume_clavier',
            new_name='resume_composition',
        ),
        migrations.AlterField(
            model_name='orgue',
            name='buffet',
            field=models.TextField(blank=True, help_text='Description du buffet et de son état.', null=True, verbose_name='Description du buffet'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='console',
            field=models.TextField(blank=True, help_text="Description de la console (ex: en fenêtre,                                séparée organiste tourné vers l'orgue ...).", null=True, verbose_name='Description de la console'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='diapason',
            field=models.CharField(blank=True, help_text='Hauteur en Hertz du A2 joué par le prestant 4, à une température donnée', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='proprietaire',
            field=models.CharField(choices=[('commune', 'Commune'), ('etat', 'Etat'), ('association_culturelle', 'Association culturelle'), ('diocese', 'Diocèse'), ('paroisse', 'Paroisse')], default='commune', max_length=20, null=True, verbose_name='Propriétaire'),
        ),
    ]
