# Generated by Django 2.2.7 on 2020-02-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0011_auto_20200210_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='tirage_commentaire',
            field=models.CharField(blank=True, help_text='Max 100 caractères', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='transmission_commentaire',
            field=models.CharField(blank=True, help_text='Max 100 caractères', max_length=100, null=True),
        ),
    ]
