# Generated by Django 2.2.13 on 2020-08-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0012_auto_20200818_1150'),
        ('orgues', '0008_auto_20200815_2227'),
    ]

    operations = [
    ]
