# Generated by Django 2.2.7 on 2020-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0012_auto_20200818_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='transmission_notes',
            field=models.CharField(blank=True, choices=[('mecanique', 'Mécanique'), ('mecanique_suspendue', 'Mécanique suspendue'), ('mecanique_balanciers', 'Mécanique à balanciers'), ('mecanique_barker', 'Mécanique Barker'), ('pneumatique_haute_pression', 'Pneumatique haute pression'), ('pneumatique_basse_pression', 'Pneumatique haute pression'), ('electrique', 'Electrique'), ('electrique_proportionnelle', 'Electrique proportionnelle'), ('electro_pneumatique', 'Electro-pneumatique')], max_length=30, null=True),
        ),
    ]
