# Generated by Django 2.2.7 on 2020-09-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0013_auto_20200820_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='legende',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
