# Generated by Django 2.2.7 on 2020-02-11 18:31

from django.db import migrations, models
import orgues.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0013_auto_20200210_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clavier',
            options={'verbose_name': 'Plan sonore'},
        ),
        migrations.RemoveField(
            model_name='clavier',
            name='facteur',
        ),
        migrations.AlterField(
            model_name='clavier',
            name='etendue',
            field=models.CharField(blank=True, help_text='De la forme F1-G5, C1-F#5 ... ', max_length=10, null=True, validators=[orgues.models.validate_etendue]),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='code_departement',
            field=models.CharField(max_length=5, verbose_name='Code département'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='commentaire_tuyauterie',
            field=models.TextField(blank=True, verbose_name='Description de la tuyauterie'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='departement',
            field=models.CharField(max_length=50, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='region',
            field=models.CharField(max_length=50, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='tirage_jeux',
            field=models.CharField(blank=True, choices=[('mecanique', 'Mécanique'), ('pneumatique', 'Pneumatique'), ('electrique', 'Electrique'), ('electro-pneumatique', 'Electro-pneumatique')], max_length=20, null=True, verbose_name='Tirage des jeux'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='transmission_notes',
            field=models.CharField(blank=True, choices=[('mecanique', 'Mécanique'), ('mecanique_suspendue', 'Mécanique suspendue'), ('mecanique_balanciers', 'Mécanique à balanciers'), ('mecanique_barker', 'Mécanique Barker'), ('pneumatique', 'Pneumatique'), ('electrique', 'Electrique'), ('electrique_proportionnelle', 'Electrique proportionnelle'), ('electro-pneumatique', 'Electro-pneumatique')], max_length=20, null=True),
        ),
    ]
