# Generated by Django 2.2.7 on 2020-09-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0014_image_legende'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgue',
            options={'ordering': ['-created_date'], 'permissions': [('edition_avancee', "Peut modifier les champs structurels d'un orgue (ex : code_insee ...)")]},
        ),
    ]
