# Generated by Django 2.2.7 on 2020-09-04 11:27

from django.db import migrations, models
import orgues.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0015_auto_20200904_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Taille maximale : 4Mo', upload_to=orgues.models.chemin_image),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('node', 'Nœud'), ('way', 'Chemin'), ('relation', 'Relation')], max_length=20, null=True, verbose_name='Type open street map'),
        ),
    ]
