# Generated by Django 2.2.7 on 2020-03-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0016_auto_20200211_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgue',
            name='console',
            field=models.TextField(blank=True, help_text="Description de la console (ex: en fenêtre, séparée organiste tourné vers l'orgue ...).", null=True, verbose_name='Description console'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='diapason',
            field=models.CharField(blank=True, help_text='Hauteur en Hertz du A2 joué par le prestant 4', max_length=15, null=True),
        ),
    ]
