# Generated by Django 2.2.7 on 2020-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0016_auto_20200211_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgue',
            name='keywords',
            field=models.TextField(default='orgue'),
            preserve_default=False,
        ),
    ]
