# Generated by Django 2.2.13 on 2020-09-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0014_auto_20200818_2050'),
        ('orgues', '0016_auto_20200904_1127'),
    ]

    operations = [
    ]
