# Generated by Django 2.2.7 on 2020-09-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0016_auto_20200904_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgue',
            name='temperament',
            field=models.CharField(blank=True, help_text='Mention la plus précise possible. Ex: mésotonique au sixième modifié.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clavier',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgues.TypeClavier', verbose_name='Nom'),
        ),
    ]
