# Generated by Django 2.2.7 on 2020-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0017_auto_20200907_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='keywords',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='proprietaire',
            field=models.CharField(choices=[('commune', 'Commune'), ('etat', 'Etat'), ('association_culturelle', 'Association culturelle'), ('diocese', 'Diocèse'), ('paroisse', 'Paroisse')], default='commune', max_length=40, null=True, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
