# Generated by Django 2.2.7 on 2020-06-09 14:57

from django.db import migrations
import imagekit.models.fields
import orgues.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0018_auto_20200602_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_principale',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to=orgues.models.chemin_image),
            preserve_default=False,
        ),
    ]
