# Generated by Django 2.2.7 on 2020-06-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0019_image_thumbnail_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgue',
            name='resume_clavier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
