# Generated by Django 2.2.7 on 2020-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0020_orgue_resume_clavier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgue',
            name='facteurs',
            field=models.ManyToManyField(blank=True, to='orgues.Facteur'),
        ),
    ]
