# Generated by Django 2.2.13 on 2020-09-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0017_merge_20200904_2205'),
        ('orgues', '0020_auto_20200909_1642'),
    ]

    operations = [
    ]
