# Generated by Django 2.2.7 on 2020-09-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0020_auto_20200909_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgue',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='orgue',
            name='emplacement',
            field=models.CharField(blank=True, help_text='Ex: sol, tribune ...', max_length=50, null=True, verbose_name='Emplacement'),
        ),
    ]
