# Generated by Django 2.2.7 on 2020-06-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0021_orgue_facteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='facteurs',
            field=models.ManyToManyField(blank=True, editable=False, to='orgues.Facteur'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='resume_clavier',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
