# Generated by Django 2.2.7 on 2020-11-11 10:50

from django.db import migrations, models
import orgues.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0021_auto_20200912_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='resume',
            field=models.TextField(blank=True, help_text='700 caractères max', max_length=700, null=True, verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='image',
            name='credit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Crédit'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Taille maximale : 2 Mo', upload_to=orgues.models.chemin_image),
        ),
        migrations.AlterField(
            model_name='image',
            name='legende',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Légende'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='references_palissy',
            field=models.CharField(blank=True, help_text='Séparer les codes par des virgules', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='resume',
            field=models.TextField(blank=True, help_text="Présentation en quelques lignes de l'instrument                               et son originalité (max 500 caractères)", max_length=500, null=True, verbose_name='Résumé'),
        ),
    ]
