# Generated by Django 2.2.7 on 2020-11-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0022_auto_20201111_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgue',
            name='facteurs',
        ),
        migrations.AlterField(
            model_name='orgue',
            name='temperament',
            field=models.CharField(blank=True, help_text='Mention la plus précise possible. Ex: mésotonique au sixième modifié.', max_length=50, null=True, verbose_name='Tempérament'),
        ),
    ]
