# Generated by Django 2.2.13 on 2020-11-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0023_auto_20201112_1724'),
        ('orgues', '0021_auto_20200912_1505'),
    ]

    operations = [
    ]
