# Generated by Django 2.2.13 on 2021-03-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0027_auto_20201218_1600'),
        ('orgues', '0021_merge_20200914_1025'),
    ]

    operations = [
    ]
