# Generated by Django 2.2.13 on 2021-03-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0028_merge_20210307_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='facteur',
            name='latitude_atelier',
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude de l'atelier"),
        ),
        migrations.AddField(
            model_name='facteur',
            name='longitude_atelier',
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude de l'atelier"),
        ),
        migrations.AddField(
            model_name='orgue',
            name='entretien',
            field=models.ManyToManyField(blank=True, to='orgues.Facteur', verbose_name="Facteur en charge de l'entretien"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type',
            field=models.CharField(choices=[('construction', 'Construction'), ('inauguration', 'Inauguration'), ('reconstruction', 'Reconstruction'), ('destruction', 'Destruction'), ('restauration', 'Restauration'), ('deplacement', 'Déplacement'), ('relevage', 'Relevage'), ('modifications', 'Modifications'), ('disparition', 'Disparition'), ('degats', 'Dégâts'), ('classement_mh', 'Classement au titre des monuments historiques'), ('inscription_mh', 'Inscription au titre des monuments historiques')], max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='credit',
            field=models.CharField(default='Non renseigné', max_length=200, verbose_name='Crédit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgue',
            name='codification',
            field=models.CharField(db_index=True, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='etat',
            field=models.CharField(blank=True, choices=[('tres_bon', 'Très bon, tout à fait jouable'), ('bon', 'Bon : jouable, défauts mineurs'), ('altere', 'Altéré : difficilement jouable'), ('degrade', 'Dégradé ou en ruine : injouable')], help_text="Se rapporte au fait que l'orgue est jouable ou non.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='proprietaire',
            field=models.CharField(choices=[('commune', 'Commune'), ('etat', 'Etat'), ('association_culturelle', 'Association culturelle'), ('diocese', 'Diocèse'), ('paroisse', 'Paroisse'), ('congregation', 'Congrégation')], default='commune', max_length=40, null=True, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='references_palissy',
            field=models.CharField(blank=True, help_text='Séparer les codes par des virgules', max_length=60, null=True, verbose_name='Référence(s) Palissy'),
        ),
    ]
