# Generated by Django 2.2.7 on 2021-03-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgues', '0030_auto_20210312_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='typejeu',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typejeu',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AddField(
            model_name='typejeu',
            name='updated_by_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
