# Generated by Django 2.2.7 on 2021-03-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0031_auto_20210316_1125'),
        ('orgues', '0031_auto_20210316_1445'),
    ]

    operations = [
    ]
