# Generated by Django 2.2.7 on 2021-03-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0032_merge_20210316_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='annee_fin',
            field=models.IntegerField(blank=True, null=True, verbose_name="Année de fin de l'évènement"),
        ),
        migrations.AddField(
            model_name='evenement',
            name='circa',
            field=models.BooleanField(default=False, verbose_name='Dates approximatives'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='annee',
            field=models.IntegerField(verbose_name="Année de début de l'évènement"),
        ),
    ]
