# Generated by Django 2.2.13 on 2021-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0032_merge_20210316_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('node', 'Nœud (Node)'), ('way', 'Chemin (Way)'), ('relation', 'Relation (Relation)')], max_length=20, null=True, verbose_name='Type open street map'),
        ),
    ]
