# Generated by Django 2.2.13 on 2021-03-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0033_auto_20210320_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='annee_fin',
            field=models.IntegerField(blank=True, help_text='Optionnelle', null=True, verbose_name="Année de fin de l'évènement"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='circa',
            field=models.BooleanField(default=False, verbose_name='Cocher si dates approximatives'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='etat',
            field=models.CharField(blank=True, choices=[('tres_bon', 'Très bon, tout à fait jouable'), ('bon', 'Bon : jouable, défauts mineurs'), ('altere', 'Altéré : difficilement jouable'), ('degrade', 'Dégradé ou en ruine : injouable'), ('restauration', 'En restauration (ou projet initié)')], help_text="Se rapporte au fait que l'orgue est jouable ou non.", max_length=20, null=True),
        ),
    ]
