# Generated by Django 2.2.13 on 2021-04-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facteur',
            options={'ordering': ['latitude_atelier']},
        ),
    ]
