# Generated by Django 2.2.7 on 2021-03-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0034_auto_20210321_2255'),
        ('orgues', '0036_auto_20210322_0115'),
    ]

    operations = [
    ]
