# Generated by Django 3.1.7 on 2021-04-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0036_auto_20210322_0115'),
        ('orgues', '0033_auto_20210322_1938'),
    ]

    operations = [
    ]
