# Generated by Django 3.1.7 on 2021-03-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0033_auto_20210322_1938'),
        ('orgues', '0038_auto_20210323_0848'),
    ]

    operations = [
    ]
