# Generated by Django 2.2.13 on 2021-04-20 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgues', '0038_auto_20210420_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributions',
            new_name='Contribution',
        ),
    ]
