# Generated by Django 2.2.13 on 2021-04-26 12:01

from django.db import migrations
from orgues.models import Orgue, Contribution
from accounts.models import User

def init_contributions(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Orgue = apps.get_model('orgues', 'Orgue')
    for orgue in Orgue.objects.all():
        if orgue.updated_by_user is not None:
            contribution = Contribution()
            contribution.user_id = orgue.updated_by_user_id
            contribution.date = orgue.modified_date
            contribution.orgue_id = orgue.id
            contribution.description = "Mise à jour"
            contribution.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0039_auto_20210420_2119'),
    ]

    operations = [
        migrations.RunPython(init_contributions),
    ]
