# Generated by Django 3.1.8 on 2021-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0039_auto_20210423_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgue',
            name='references_inventaire_regions',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Code inventaire régional'),
        ),
    ]
