# Generated by Django 3.1.8 on 2021-05-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0040_orgue_references_inventaire_regions'),
        ('orgues', '0041_auto_20210426_1229'),
    ]

    operations = [
    ]
