# Generated by Django 3.1.8 on 2021-05-07 14:48

from django.db import migrations, models
import orgues.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0042_merge_20210507_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clavier',
            name='commentaire',
            field=models.CharField(blank=True, help_text='Particularités specifiques du clavier (transmission, ravalement, etc.)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clavier',
            name='etendue',
            field=models.CharField(blank=True, help_text='De la forme F1-G5, C1-F#5, CD1-G5 (pour absence premier Ut dièse)...', max_length=10, null=True, validators=[orgues.models.validate_etendue]),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='accessoires',
            field=models.ManyToManyField(blank=True, help_text='Nous contacter si un accessoire manque.', to='orgues.Accessoire'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='commentaire_admin',
            field=models.TextField(blank=True, help_text='Commentaire uniquement visible par les contributeurs.', null=True, verbose_name='Commentaire contributeurs'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='diapason',
            field=models.CharField(blank=True, help_text='Hauteur en Hertz du A2 joué par le prestant 4, à une température donnée.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='organisme',
            field=models.CharField(blank=True, help_text="Notamment pour accéder à l'instrument.", max_length=100, null=True, verbose_name="Organisme auquel s'adresser"),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='osm_id',
            field=models.CharField(blank=True, help_text="Id OSM de l'objet décrivant l'édifice.", max_length=20, null=True, verbose_name='Id open street map'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('node', 'Nœud (Node)'), ('way', 'Chemin (Way)'), ('relation', 'Relation (Relation)')], help_text="Type OSM de l'objet représenant l'édifice.", max_length=20, null=True, verbose_name='Type open street map'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='references_palissy',
            field=models.CharField(blank=True, help_text='Séparer les codes par des virgules.', max_length=60, null=True, verbose_name='Référence(s) Palissy pour les monuments historiques.'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='resume',
            field=models.TextField(blank=True, help_text="Présentation en quelques lignes de l'instrument                               en insistant sur son originalité (max 500 caractères).", max_length=500, null=True, verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='tirage_commentaire',
            field=models.CharField(blank=True, help_text='Max 100 caractères.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='transmission_commentaire',
            field=models.CharField(blank=True, help_text='Max 100 caractères.', max_length=100, null=True),
        ),
    ]
