# Generated by Django 3.1.8 on 2021-05-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0043_auto_20210507_1342'),
        ('orgues', '0043_auto_20210507_1448'),
    ]

    operations = [
    ]
