# Generated by Django 3.1.8 on 2021-05-11 10:36

from django.db import migrations, models
import orgues.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0044_merge_20210511_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clavier',
            name='etendue',
            field=models.CharField(blank=True, help_text='De la forme F1-G5, CD1-G5 (pour absence premier Ut dièse), FGC1-G5 (pour un ravalement), ...', max_length=10, null=True, validators=[orgues.models.validate_etendue]),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='osm_id',
            field=models.CharField(blank=True, help_text="Id OSM de l'objet décrivant l'édifice.", max_length=20, null=True, verbose_name='Id open street map'),
        ),
    ]
