# Generated by Django 3.1.8 on 2021-05-25 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0046_auto_20210511_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='annee',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Une année !', regex='^[1-2][0-9][0-9][0-9]$')], verbose_name="Année de début de l'évènement"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='annee_fin',
            field=models.PositiveIntegerField(blank=True, help_text='Optionnelle', null=True, validators=[django.core.validators.RegexValidator(message='Une année !', regex='^[1-2][0-9][0-9][0-9]$')], verbose_name="Année de fin de l'évènement"),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='designation',
            field=models.CharField(blank=True, default='orgue', help_text='orgue de tribune, orgue coffre, etc.', max_length=50, null=True, verbose_name="Désignation de l'instrument"),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='emplacement',
            field=models.CharField(blank=True, help_text='Ex: sol, tribune ...', max_length=100, null=True, verbose_name='Emplacement'),
        ),
    ]
