# Generated by Django 3.1.8 on 2021-05-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0048_auto_20210518_1715'),
        ('orgues', '0047_auto_20210525_1745'),
    ]

    operations = [
    ]
