# Generated by Django 3.1.8 on 2021-05-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0049_merge_20210528_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='annee',
            field=models.IntegerField(verbose_name="Année de début de l'évènement"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='annee_fin',
            field=models.IntegerField(blank=True, help_text='Optionnelle', null=True, verbose_name="Année de fin de l'évènement"),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='designation',
            field=models.CharField(blank=True, default='orgue', max_length=300, null=True, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='emplacement',
            field=models.CharField(blank=True, help_text='Ex: sol, tribune ...', max_length=50, null=True, verbose_name='Emplacement'),
        ),
    ]
