# Generated by Django 3.1.12 on 2021-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0050_auto_20210528_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='lien_reference',
            field=models.URLField(blank=True, help_text="Lien internet de l'organisme auquel s'adresser.", max_length=300, null=True, verbose_name='Lien de référence'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='osm_id',
            field=models.CharField(blank=True, help_text="Identifiant OSM de l'objet décrivant l'édifice.", max_length=20, null=True, verbose_name='Id OpenStreetMap'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('node', 'Nœud (Node)'), ('way', 'Chemin (Way)'), ('relation', 'Relation (Relation)')], help_text="Type OSM de l'objet représenant l'édifice.", max_length=20, null=True, verbose_name='Type OpenStreetMap'),
        ),
    ]
