# Generated by Django 3.1.12 on 2021-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0052_auto_20210816_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='configuration',
            field=models.CharField(blank=True, choices=[('basse', 'Basse'), ('dessus', 'Dessus'), ('basse_et_dessus', 'Basse et Dessus séparés')], max_length=20, null=True),
        ),
    ]
