# Generated by Django 3.1.12 on 2021-09-04 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0054_auto_20210903_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Renseigner une latitude valide', regex='^([-]?([0-9]|[0-8][0-9])[.][0-9]*)$')]),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Renseigner une longitude valide', regex='^([-]?([0-9]|[0-9][0-9]|1[0-7][0-9])[.][0-9]*)$')]),
        ),
    ]
