# Generated by Django 3.1.12 on 2021-09-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0055_auto_20210904_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='designation',
            field=models.CharField(blank=True, default='orgue', help_text="Type d'orgue : grand orgue, orgue coffre, orgue portatif, etc.", max_length=300, null=True, verbose_name="Désignation de l'orgue"),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='emplacement',
            field=models.CharField(blank=True, help_text="Emplacement dans l'édifice : sol, tribune, crypte ...", max_length=60, null=True, verbose_name='Emplacement'),
        ),
    ]
