# Generated by Django 3.1.12 on 2021-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0056_auto_20210909_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgue',
            name='proprietaire',
            field=models.CharField(choices=[('commune', 'Commune'), ('interco', 'Intercommunalité'), ('etat', 'Etat'), ('association_culturelle', 'Association culturelle'), ('diocese', 'Diocèse'), ('paroisse', 'Paroisse'), ('congregation', 'Congrégation'), ('etablissement_scolaire', 'Etablissement scolaire'), ('conservatoire', 'Conservatoire ou Ecole de musique'), ('hopital', 'Hôpital'), ('particulier', 'Particulier (propriété privée)')], default='commune', max_length=40, null=True, verbose_name='Propriétaire'),
        ),
    ]
