# Generated by Django 3.1.12 on 2021-11-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0057_auto_20210909_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessoire',
            options={'ordering': ['nom']},
        ),
    ]
