# Generated by Django 3.1.13 on 2022-01-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0058_auto_20211113_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clavier',
            name='type',
            field=models.ForeignKey(help_text="Pensez à utiliser le clavier... d'ordinateur pour compléter aisément les longs formulaires : [Tab]: avancer, [Maj+Tab] : reculer, [Espace] : dérouler, [Haut/Bas] : choisir.", null=True, on_delete=django.db.models.deletion.CASCADE, to='orgues.typeclavier', verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='commentaire_admin',
            field=models.TextField(blank=True, help_text='Commentaire uniquement visible par les contributeurs, par exemple pour indiquer un doute ou point à creuser. Inutile de mentionner la date de contribution déjà enregistrée par ailleurs. Pour contacter les administrateurs, rédigez un courriel.', null=True, verbose_name='Commentaire contributeurs'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('node', 'Nœud (Node)'), ('way', 'Chemin (Way)'), ('relation', 'Relation (Relation)')], default='way', help_text="Type OSM de l'objet représenant l'édifice.", max_length=20, null=True, verbose_name='Type OpenStreetMap'),
        ),
    ]
