# Generated by Django 3.1.14 on 2022-02-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0059_auto_20220105_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('disque', 'Disque'), ('web', 'Web'), ('ouvrage', 'Ouvrage'), ('video', 'Video'), ('visite', "Visite de l'orgue")], max_length=20, verbose_name='Type de source'),
        ),
    ]
