# Generated by Django 3.1.14 on 2022-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0060_auto_20220227_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgue',
            name='qualification_palissy',
            field=models.CharField(blank=True, choices=[('orgue_de_tribune', 'orgue de tribune'), ('orgue_de_choeur', 'orgue de choeur'), ('orgue_a_cylindres', 'orgue à cylindres'), ('orgue_a_manivelle', 'orgue à manivelle'), ('orgue_de_triforium', 'orgue de triforium'), ('orgue_portatif', 'orgue portatif'), ('orgue_de_cabinet / salon', 'orgue de cabinet / salon')], help_text="Qualification de l'orgue dans Palissy", max_length=24, null=True, verbose_name=''),
        ),
    ]
