# Generated by Django 3.1.14 on 2022-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0061_orgue_qualification_palissy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgue',
            name='lien_inventaire_regions',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name="Lien vers l'inventaire régional"),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='qualification_palissy',
            field=models.CharField(blank=True, choices=[('orgue_de_tribune', 'orgue de tribune'), ('orgue_de_choeur', 'orgue de choeur'), ('orgue_a_cylindres', 'orgue à cylindres'), ('orgue_a_manivelle', 'orgue à manivelle'), ('orgue_de_triforium', 'orgue de triforium'), ('orgue_portatif', 'orgue portatif'), ('orgue_de_cabinet / salon', 'orgue de cabinet / salon')], help_text="Si inscrit ou classé, qualification de l'orgue, dans Palissy", max_length=24, null=True, verbose_name='Dénomination dans Palissy'),
        ),
    ]
