# Generated by Django 3.1.14 on 2022-11-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0063_auto_20221111_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='type',
            field=models.CharField(choices=[('construction', 'Construction'), ('inauguration', 'Inauguration'), ('reconstruction', 'Reconstruction'), ('destruction', 'Destruction'), ('restauration', 'Restauration'), ('reparation', 'Réparation'), ('deplacement', 'Déplacement'), ('demontage', 'Démontage et stockage'), ('relevage', 'Relevage'), ('modifications', 'Modifications'), ('disparition', 'Disparition'), ('degats', 'Dégâts'), ('classement_mh', 'Classement au titre des monuments historiques'), ('inscription_mh', 'Inscription au titre des monuments historiques')], max_length=20),
        ),
    ]
