# Generated by Django 3.1.12 on 2023-04-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0064_auto_20221111_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgue',
            name='buffet_vide',
            field=models.BooleanField(default=False, verbose_name='Orgue sans tuyaux'),
        ),
    ]
