# Generated by Django 3.1.14 on 2023-11-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0066_auto_20231101_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Localisation',
            new_name='Provenance',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='localisation',
        ),
        migrations.AddField(
            model_name='evenement',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgues.provenance', verbose_name='Provenance'),
        ),
    ]
