# Generated by Django 3.1.14 on 2024-02-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0067_auto_20231103_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='facteur',
            name='annee_deces',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de décès'),
        ),
        migrations.AddField(
            model_name='facteur',
            name='annee_naissance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de naissance'),
        ),
        migrations.AlterField(
            model_name='orgue',
            name='etat',
            field=models.CharField(blank=True, choices=[('tres_bon', 'Très bon, tout à fait jouable'), ('bon', 'Bon : jouable, défauts mineurs'), ('altere', 'Altéré : difficilement jouable'), ('degrade', 'Dégradé ou en ruine : injouable'), ('restauration', 'En restauration (ou projet initié)'), ('disparu', 'Disparu')], help_text="Se rapporte au fait que l'orgue est jouable ou non.", max_length=20, null=True),
        ),
    ]
