# Generated by Django 3.1.14 on 2024-03-29 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0068_auto_20240205_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacteurManufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField(blank=True, null=True, verbose_name="Année d'entrée dans la manufacture'")),
                ('annee_fin', models.IntegerField(blank=True, null=True, verbose_name='Année de sortie de la manufacture')),
                ('facteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facteurManufacture', to='orgues.facteur')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('facteur', models.ManyToManyField(blank=True, null=True, related_name='manufacture', to='orgues.FacteurManufacture', verbose_name='Facteur ayant travaillé dans la manufacture')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='manufactures',
            field=models.ManyToManyField(blank=True, related_name='evenements', to='orgues.Manufacture'),
        ),
    ]
