# Generated by Django 3.1.14 on 2024-08-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0070_auto_20240329_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacture',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='orgue',
            name='entretienManufacture',
            field=models.ManyToManyField(blank=True, to='orgues.Manufacture', verbose_name="Manufacture en charge de l'entretien"),
        ),
    ]
