# Generated by Django 5.1.6 on 2025-02-20 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0071_auto_20240827_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='emprunt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgues.jeu'),
        ),
    ]
