# Generated by Django 5.1.6 on 2026-02-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgues', '0072_jeu_emprunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='type',
            field=models.CharField(choices=[('construction', 'Construction'), ('inauguration', 'Inauguration'), ('reconstruction', 'Reconstruction'), ('destruction', 'Destruction'), ('restauration', 'Restauration'), ('reparation', 'Réparation'), ('deplacement', 'Déplacement'), ('demontage', 'Démontage et stockage'), ('relevage', 'Relevage'), ('modifications', 'Modifications'), ('disparition', 'Disparition'), ('degats', 'Dégâts'), ('classement_mh', 'Classement au titre des monuments historiques'), ('inscription_mh', 'Inscription au titre des monuments historiques'), ('remise_en_service', 'Remise en service'), ('depoussierage', 'Dépoussiérage')], max_length=20),
        ),
    ]
