# Generated by Django 2.2.13 on 2021-03-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210312_2143'),
        ('accounts', '0002_auto_20210316_1125'),
    ]

    operations = [
    ]
