# Generated by Django 3.1.7 on 2021-03-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210323_0848'),
        ('accounts', '0003_merge_20210321_2254'),
    ]

    operations = [
    ]
