# Generated by Django 2.2.13 on 2021-04-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210317_1207'),
        ('accounts', '0005_auto_20210414_1448'),
    ]

    operations = [
    ]
