# Generated by Django 3.1.8 on 2021-05-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20210427_0845'),
        ('accounts', '0006_auto_20210423_2154'),
    ]

    operations = [
    ]
