# Generated by Django 3.1.8 on 2021-05-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210504_1200'),
        ('accounts', '0007_auto_20210503_1542'),
        ('accounts', '0007_merge_20210504_1328'),
    ]

    operations = [
    ]
