# Generated by Django 3.1.8 on 2021-05-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20210507_1004'),
        ('accounts', '0005_auto_20210420_1913'),
        ('accounts', '0007_auto_20210503_1542'),
    ]

    operations = [
    ]
