# Generated by Django 3.1.8 on 2021-05-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20210507_1135'),
        ('accounts', '0009_merge_20210507_1310'),
    ]

    operations = [
    ]
