# Generated by Django 3.1.8 on 2021-05-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20210506_1407'),
        ('accounts', '0012_merge_20210511_1026'),
    ]

    operations = [
    ]
